### ISSUE TITLE
lni – german

### ISSUE THREAD

**Issue by lhumb** [adbrucker/authorarchive#18]
Thanks for this package, which we want to use, but there are two problems:

We want to use authorarchive with _biblatex_ and with the german-version of the lni-package to use it for publications for GI-Fachtagung Informatik und Schule (INFOS).

Therefor the entry in our publication-bib-files are not using the field year anymore, but date, so we want to be able to use
date={2019-09-18},
instead of
year={2019},

TNX 
Ludger

**Comment by adbrucker** [comment]
Hi,
Could you please provide an minimal example (no worries, if it is in German) that demonstrates the problem. 

As the date argument of the \usepackage{}-command is only used for generating the self-archiving note (citation) that is usually put on the front page, there should be no problem. The package \authorarchive{} does not analyse the BibTeX-Entry itself. 

Thanks a lot!

Best,
Achim

**Comment by lhumb** [comment]
When typesetting with 
> pdflatex lni-author-template
getting the included cite with
> biber lni-author-template

I get:
! Package authorarchive Error: No bibliographic files found. Specify option 'no                                                                         
bib' if this is intended..
See the authorarchive package documentation for explanation.
Type  H <return>  for immediate help.
 ...
l.89 \end{document}

[die-anonyme-bibliografie.bib.txt](https://github.com/adbrucker/authorarchive/files/3609081/die-anonyme-bibliografie.bib.txt)
[lni-author-template.tex.txt](https://github.com/adbrucker/authorarchive/files/3609088/lni-author-template.tex.txt)

**Comment by lhumb** [comment]
Hi Achim,
we get–when ignoring the error pdflatex–a mostly correct output, I think
[lni-author-template.pdf](https://github.com/adbrucker/authorarchive/files/3609110/lni-author-template.pdf)
I mentioned the year- versus date- entry, because I love orthogonality ;-) 
not only in programming, but also in working with data …

Thank you for answering my questions …
Ludger

**Comment by adbrucker** [comment]
Hi,
By default, authoarchive tries to include BibTeX-file for the paper (and files for Endnote and/or Word, if available) into the PDF so that people reading the paper have a nice BibTeX entry readily available. For this, authorarchive searches for files using they "key" value as name (adding the format specific extension, e.g., .bib) in the bibtexdir (default: local directory). 

If you do not want the BibTeX file included, please specify the nobib option, telling authorarchive that it should not try to embed these files.

Best,
Achim

**Comment by lhumb** [comment]
Hi,
I added the file *die-anonyme-bibliografie.bib* in the local directory … but the error remains … perhaps I made an error … I'll look over my local directory once more … to see, where my error may be…

Best,
Ludger

**Comment by adbrucker** [comment]
Hi,
Note that if you have

\usepackage[key=foo, ...]{} the package will look for foo.bib and include the whole file. It is assumed that the file only contains the bib entry for the paper itself.

Achim

**Comment by lhumb** [comment]
Dear Achim,
thank you – I'll try ti immediatly ;-)

Ludger

**Comment by lhumb** [comment]
<QR code requested for "https://ddi.uni-wuppertal.de/Nachname1Nachname2-2021.pd                                                                         
f" in version 0-M.>

<Copying the QR code for "https://ddi.uni-wuppertal.de/Nachname1Nachname2-2021.                                                                         
pdf" in version 4-M as previously calculated.>

Overfull \hbox (1.52605pt too wide) has occurred while \output is active
[][]$[]$[][]
(/lh-pool/usr/local/texlive/2019/texmf-dist/tex/latex/newtxtt/t1newtxtt.fd)<<./                                                                         
/Nachname1Nachname2-2021.bib>>
! Use of \BibTeX doesn't match its definition.
\__intopdf_annot:nnn ...2}#3\__intopdf_annot_end:

l.103

**Comment by lhumb** [comment]
One problem seems to be:
\documentclass[biblatex]{lni} => ! LaTeX Error: Option clash for package hyperref.     
[but no hyperrefs are produced -- error remains]

\documentclass[nohyperref,biblatex]{lni} => hyperrefs are produced, but error remains

**Comment by lhumb** [comment]
giving up for now …

**Comment by sieversMartin** [comment]
Problem can be solved by using `\AtEndPreamble` to postpone loading of authorarchive.

**Comment by adbrucker** [comment]
Hi,
Thanks a lot. This is indeed the right way for using the latest lni.cls with authorarchive, as lni.cls loads hyperref also within a \AtEndPreamble-hook. I updated the example in 70f2c954084bd4cb9104fa5722a98e72b4bf5568 

This does not (yet) solve all problems of @lhumb - there is also a problem that authorarchive does not work with the latest version of dtk-logos.sty. I will investigate this now ...

Best,
Achim

**Comment by adbrucker** [comment]
Hi,
> This does not (yet) solve all problems of @lhumb - there is also a problem that authorarchive does not work with the latest version of dtk-logos.sty. I will investigate this now ...

The " Use of \BibTeX doesn't match its definition." error is caused by the latest version of dtk-logos.sty (used by authorarchive).  I created an issue for dtk-logos.sty: https://github.com/rolfn/dtk/issues/13 as this problem also occurs for a minimal example not using authorarchive.

Best,
Achim

**Comment by lhumb** [comment]
In the meantime Herbert submitted a [new version of dtk-logos.sty](https://github.com/rolfn/dtk/commit/d72ce05439f0060b0496ab9e5e8c8f0b13392794) 
 This solves the problem [rolfn/dtk#13](https://github.com/rolfn/dtk/issues/13) 
Thank you so very much!

**Comment by lhumb** [comment]
Problem solved:  [dtk-logos.sty](https://github.com/rolfn/dtk/issues/13) 
Achim, Martin, Herbert
Thank you very much!
